version: '3'

services:
  halide:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./container_volume/:/volume
    container_name: Halide


#####################################################################
# To run the docker compose FOR THE FIRST TIME use these commands
#   docker-compose up --build
#
# To run the docker compose AFTER THE FIRST TIME use these commands
#   docker-compose run halide
#####################################################################

